name: v2.0 Build

# Run workflow on manually
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Generate coverage report
        run: |
          ./gradlew build
        working-directory: .
      - uses: codecov/codecov-action@v2
        with:
          files: build/jacoco/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
          java-version: 11
