name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current

      - name: Gradle Build and Test
        run: gradle --build-cache --configuration-cache build test koverXmlReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: '**/build/reports/kover/report.xml'
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
        if: github.ref == 'refs/heads/main'

#  security-gates:
#    needs: build-and-test  # Run after build succeeds
#    uses: Trendyol/security-actions/.github/workflows/security-gates.yml@master
#    permissions:
#      actions: read
#      contents: read
#      security-events: write
