name: Build

on:
  push:
    branches: [2.x]
  pull_request:
    branches: [2.x]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Check out Git repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Gradle Build
        run: |
           ./gradlew build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./build/jacoco/codeCoverageReport/codeCoverageReport.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
          java-version: 11
