name: Build

on:
  push:
    branches: [main, 2.x]
  pull_request:
    branches: [main, 2.x]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Check out Git repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Gradle Build
        run: |
           ./gradlew build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./build/jacoco/codeCoverageReport/codeCoverageReport.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
          java-version: 17
        if: github.ref == 'refs/heads/main'
