name: Publish to Maven

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: current

      - name: Gradle Build and Test
        run: gradle --no-configuration-cache publish
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.gpg_private_key }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.gpg_passphrase }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.sonartype_username }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.sonartype_password }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
