name: Release kediatR-quarkus-starter

# Run workflow on manually
on: [ workflow_dispatch ]
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Generate coverage report
        run: |
          mvn clean verify
        with:
          directory: kediatr-quarkus-starter
      - uses: codecov/codecov-action@v2
        with:
          files: target/site/jacoco/jacoco.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
          java-version: 11

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
          directory: kediatr-quarkus-starter
